FROM bellamy/wallos:latest

WORKDIR /var/www/html

COPY . .

RUN sed -i 's/\r$//' /var/www/html/startup.sh && \
    chown -R www-data:www-data /var/www/html && \
    chmod +x /var/www/html/startup.sh
