services:
  wallos:
    build:
      context: .
      dockerfile: Dockerfile.local
    image: wallos-remastered:latest
    container_name: wallos-remastered
    ports:
      - "18282:80/tcp"
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - './db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
      - './backups:/var/www/html/backups'
    restart: unless-stopped
