<?php

if (!defined('WALLOS_LOGIN_RATE_LIMIT_WINDOW_SECONDS')) {
    define('WALLOS_LOGIN_RATE_LIMIT_WINDOW_SECONDS', 15 * 60);
}

if (!defined('WALLOS_LOGIN_RATE_LIMIT_MAX_ATTEMPTS')) {
    define('WALLOS_LOGIN_RATE_LIMIT_MAX_ATTEMPTS', 8);
}

if (!defined('WALLOS_LOGIN_RATE_LIMIT_BLOCK_SECONDS')) {
    define('WALLOS_LOGIN_RATE_LIMIT_BLOCK_SECONDS', 15 * 60);
}

if (!defined('WALLOS_LOGIN_ATTEMPT_RETENTION_DAYS')) {
    define('WALLOS_LOGIN_ATTEMPT_RETENTION_DAYS', 7);
}

if (!defined('WALLOS_REQUEST_LOG_RETENTION_DAYS')) {
    define('WALLOS_REQUEST_LOG_RETENTION_DAYS', 30);
}

if (!defined('WALLOS_RATE_LIMIT_USAGE_RETENTION_DAYS')) {
    define('WALLOS_RATE_LIMIT_USAGE_RETENTION_DAYS', 2);
}

if (!defined('WALLOS_SECURITY_ANOMALY_RETENTION_DAYS')) {
    define('WALLOS_SECURITY_ANOMALY_RETENTION_DAYS', 30);
}
